name: Release

on:
  push:
    branches:
      - main
      - release/*
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: go get .
      - name: Build
        env: 
          GOOS: ${{matrix.goos}}
          GOARCH: ${{matrix.goarch}}
          CGO_ENABLED: 0
        run: go build -o bin/algorun-${{matrix.goarch}}-${{matrix.goos}} *.go
      
      