name: Release

on:
  push:
    branches:
      - main
      - beta
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: go get .
      - uses: go-semantic-release/action@v1
        name: release
        id: semver
        with:
          dry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add version to env        
        run: echo "VERSION=${{ steps.semver.outputs.version }}" >> $GITHUB_ENV
      - name: Build
        env: 
          GOOS: ${{matrix.goos}}
          GOARCH: ${{matrix.goarch}}
          CGO_ENABLED: 0
        run: go build -ldflags "-X main.version=${VERSION}" -o bin/nodekit-${{matrix.goarch}}-${{matrix.goos}} *.go
      - uses: actions/upload-artifact@master
        with:
          name: nodekit-${{matrix.goarch}}-${{matrix.goos}}
          path: bin/nodekit-${{matrix.goarch}}-${{matrix.goos}}
  release:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: nodekit*
          path: ./bin
      - uses: go-semantic-release/action@v1
        name: release
        id: semver
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v${{steps.semver.outputs.version}} bin/**/*
